# Generated by Django 3.0.8 on 2020-09-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/images/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
